# From https://github.com/brandenr/swiftlintconfig

disabled_rules:
  - force_cast
  - todo

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Vendor
  - build

line_length: 150

custom_rules:
    comments_space:
        name: "Space After Comment"
        regex: '(^ *//\w+)'
        message: "There should be a space after //"
        severity: warning
    comments_capitalized_ignore_possible_code:
        name: "Capitalize First Word In Comment"
        regex: "(^ +// +(?!swiftlint)[a-z]+)"
        message: "The first word of a comment should be capitalized"
        severity: warning
    comments_capitalized_find_possible_code:
        name: "Catch Commented Out Code"
        regex: "(^ *// +(?!swiftlint)[a-z]+)"
        message: "The first word of a comment should be capitalized"
        severity: warning
    multiple_empty_lines:
        name: "Multiple Empty Lines"
        regex: '((?:\s*\n){3,})'
        message: "There are too many line breaks"
        severity: warning
    unnecessary_type:
        name: "Unnecessary Type"
        regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[\? ]*= \1'
        message: "Type Definition Not Needed"
        severity: warning
